name: mock_firebase_functions
description: Flutter plugin for mocking FirebaseFunctions calls.
repository: https://github.com/simplecohesion/mock_firebase_functions
issue_tracker: https://github.com/simplecohesion/mock_firebase_functions/issues
version: 0.0.4

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  mocktail: ^1.0.3
  cloud_functions: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
